import { insertRabbi, getRabbis, pool } from "@halacha-ai/db";

interface RabbiSeed {
  name_en: string;
  name_he: string;
  era: string;
  generation?: string;
  community: string;
  birth_year: string;
  death_year: string;
  location: string;
  bio: string;
  works: string[];
}

const RABBIS: RabbiSeed[] = [
  // --- Tannaim ---
  {
    name_en: "Rabbi Akiva",
    name_he: "רבי עקיבא",
    era: "Tanna",
    generation: "3rd generation",
    community: "General",
    birth_year: "50",
    death_year: "135",
    location: "Bnei Brak, Land of Israel",
    bio: "One of the greatest Tannaim. Began learning Torah at age 40. Developed hermeneutical principles for deriving halacha from the Torah text. Teacher of Rabbi Meir, Rabbi Shimon bar Yochai, and others. Martyred by the Romans.",
    works: [],
  },
  {
    name_en: "Rabbi Meir",
    name_he: "רבי מאיר",
    era: "Tanna",
    generation: "4th generation",
    community: "General",
    birth_year: "100",
    death_year: "160",
    location: "Land of Israel",
    bio: "Student of Rabbi Akiva and Elisha ben Avuyah. Known for his brilliance and sharp intellect. His unattributed statements form the basis of the Mishnah.",
    works: [],
  },
  {
    name_en: "Rabbi Shimon bar Yochai",
    name_he: "רבי שמעון בר יוחאי",
    era: "Tanna",
    generation: "4th generation",
    community: "General",
    birth_year: "100",
    death_year: "160",
    location: "Land of Israel",
    bio: "Student of Rabbi Akiva. Hid in a cave for 13 years from the Romans. Traditionally attributed as the author of the Zohar. His teachings emphasize the inner dimension of Torah.",
    works: ["Zohar"],
  },
  {
    name_en: "Rabbi Yehudah HaNasi",
    name_he: "רבי יהודה הנשיא",
    era: "Tanna",
    generation: "6th generation",
    community: "General",
    birth_year: "135",
    death_year: "217",
    location: "Tzippori, Land of Israel",
    bio: "Known simply as 'Rebbi.' Compiled and edited the Mishnah, the foundational text of the Oral Torah. Nasi (president) of the Sanhedrin. Descendant of Hillel.",
    works: ["Mishnah"],
  },
  {
    name_en: "Hillel the Elder",
    name_he: "הלל הזקן",
    era: "Tanna",
    generation: "1st generation",
    community: "General",
    birth_year: "-110",
    death_year: "10",
    location: "Jerusalem, Land of Israel",
    bio: "Born in Babylon, became Nasi of the Sanhedrin. Founder of the House of Hillel. Known for his humility and patience. Formulated the Golden Rule and seven hermeneutical principles.",
    works: [],
  },
  {
    name_en: "Shammai",
    name_he: "שמאי",
    era: "Tanna",
    generation: "1st generation",
    community: "General",
    birth_year: "-50",
    death_year: "30",
    location: "Jerusalem, Land of Israel",
    bio: "Av Beit Din alongside Hillel as Nasi. Founded the House of Shammai. Known for strict interpretations and uncompromising adherence to the letter of the law.",
    works: [],
  },
  {
    name_en: "Rabbi Yishmael",
    name_he: "רבי ישמעאל",
    era: "Tanna",
    generation: "3rd generation",
    community: "General",
    birth_year: "90",
    death_year: "135",
    location: "Land of Israel",
    bio: "Contemporary of Rabbi Akiva. Developed 13 hermeneutical principles for Torah interpretation. His school favored peshat (plain meaning) interpretation.",
    works: ["Mechilta de-Rabbi Yishmael"],
  },
  {
    name_en: "Rabban Gamaliel II",
    name_he: "רבן גמליאל דיבנה",
    era: "Tanna",
    generation: "2nd generation",
    community: "General",
    birth_year: "50",
    death_year: "118",
    location: "Yavneh, Land of Israel",
    bio: "Nasi of the Sanhedrin at Yavneh after the destruction of the Temple. Grandson of Rabban Gamaliel the Elder. Standardized Jewish prayer and the Passover Haggadah order.",
    works: [],
  },

  // --- Amoraim ---
  {
    name_en: "Rav (Abba Arikha)",
    name_he: "רב (אבא אריכא)",
    era: "Amora",
    generation: "1st generation",
    community: "General",
    birth_year: "175",
    death_year: "247",
    location: "Sura, Babylonia",
    bio: "Founded the great academy at Sura. Student of Rabbi Yehudah HaNasi. One of the first Babylonian Amoraim. His disputes with Shmuel form a central theme of the Babylonian Talmud.",
    works: [],
  },
  {
    name_en: "Shmuel (Mar Shmuel)",
    name_he: "שמואל (מר שמואל)",
    era: "Amora",
    generation: "1st generation",
    community: "General",
    birth_year: "165",
    death_year: "257",
    location: "Nehardea, Babylonia",
    bio: "Head of the academy at Nehardea. Expert in civil law and astronomy. Established the principle that 'the law of the land is the law' (dina d'malkhuta dina).",
    works: [],
  },
  {
    name_en: "Rav Ashi",
    name_he: "רב אשי",
    era: "Amora",
    generation: "6th generation",
    community: "General",
    birth_year: "352",
    death_year: "427",
    location: "Sura, Babylonia",
    bio: "Primary compiler and editor of the Babylonian Talmud. Head of the academy at Sura for nearly 60 years. Organized and structured the vast corpus of oral traditions.",
    works: ["Talmud Bavli"],
  },
  {
    name_en: "Rava",
    name_he: "רבא",
    era: "Amora",
    generation: "4th generation",
    community: "General",
    birth_year: "280",
    death_year: "352",
    location: "Machoza, Babylonia",
    bio: "One of the greatest Babylonian Amoraim. His disputes with Abaye are famous throughout the Talmud. In nearly all cases, the halacha follows Rava.",
    works: [],
  },
  {
    name_en: "Abaye",
    name_he: "אביי",
    era: "Amora",
    generation: "4th generation",
    community: "General",
    birth_year: "278",
    death_year: "338",
    location: "Pumbedita, Babylonia",
    bio: "Head of the academy at Pumbedita. Raised by his uncle Rabbah. Famous for his debates with Rava (the 'havayot d'Abaye v'Rava').",
    works: [],
  },
  {
    name_en: "Rabbi Yochanan",
    name_he: "רבי יוחנן",
    era: "Amora",
    generation: "2nd generation",
    community: "General",
    birth_year: "180",
    death_year: "279",
    location: "Tiberias, Land of Israel",
    bio: "Greatest of the Land of Israel Amoraim. Primary compiler of the Jerusalem Talmud. Head of the academy at Tiberias for decades.",
    works: ["Talmud Yerushalmi"],
  },
  {
    name_en: "Reish Lakish",
    name_he: "ריש לקיש",
    era: "Amora",
    generation: "2nd generation",
    community: "General",
    birth_year: "200",
    death_year: "275",
    location: "Tiberias, Land of Israel",
    bio: "Brother-in-law and study partner of Rabbi Yochanan. Former gladiator who became one of the greatest scholars. Known for his sharp analytical mind.",
    works: [],
  },

  // --- Geonim ---
  {
    name_en: "Saadia Gaon",
    name_he: "רב סעדיה גאון",
    era: "Gaon",
    community: "General",
    birth_year: "882",
    death_year: "942",
    location: "Sura, Babylonia / Egypt",
    bio: "Gaon of Sura. Philosopher, linguist, and halachist. Authored 'Emunot VeDeot' (Book of Beliefs and Opinions), the first systematic Jewish philosophical work. Translated the Torah into Arabic.",
    works: ["Emunot VeDeot"],
  },
  {
    name_en: "Rav Hai Gaon",
    name_he: "רב האי גאון",
    era: "Gaon",
    community: "General",
    birth_year: "939",
    death_year: "1038",
    location: "Pumbedita, Babylonia",
    bio: "Last major Gaon of Pumbedita. Prolific author of responsa and commentaries. His responsa addressed communities throughout the Jewish world.",
    works: [],
  },
  {
    name_en: "Rav Sherira Gaon",
    name_he: "רב שרירא גאון",
    era: "Gaon",
    community: "General",
    birth_year: "906",
    death_year: "1006",
    location: "Pumbedita, Babylonia",
    bio: "Gaon of Pumbedita and father of Rav Hai Gaon. Authored the famous 'Iggeret' (Epistle), a historical chronicle of the transmission of the Oral Torah.",
    works: ["Iggeret Rav Sherira Gaon"],
  },

  // --- Rishonim ---
  {
    name_en: "Rashi (Shlomo Yitzchaki)",
    name_he: "רש\"י (שלמה יצחקי)",
    era: "Rishon",
    community: "Ashkenazi",
    birth_year: "1040",
    death_year: "1105",
    location: "Troyes, France",
    bio: "The most widely studied commentator on the Torah and Talmud. His commentary on the Talmud is printed on every page of the standard edition. Founded a yeshiva in Troyes. His grandsons were the Tosafists.",
    works: ["Rashi on Torah", "Rashi on Talmud"],
  },
  {
    name_en: "Rambam (Moshe ben Maimon)",
    name_he: "רמב\"ם (משה בן מימון)",
    era: "Rishon",
    community: "Sephardi",
    birth_year: "1138",
    death_year: "1204",
    location: "Cordoba / Fez / Cairo",
    bio: "Greatest Jewish philosopher and codifier. Physician to the Sultan of Egypt. His Mishneh Torah is the first complete codification of Jewish law. The Guide for the Perplexed is the pinnacle of Jewish philosophy.",
    works: ["Mishneh Torah", "Guide for the Perplexed", "Commentary on the Mishnah", "Sefer HaMitzvot"],
  },
  {
    name_en: "Ramban (Moshe ben Nachman)",
    name_he: "רמב\"ן (משה בן נחמן)",
    era: "Rishon",
    community: "Sephardi",
    birth_year: "1194",
    death_year: "1270",
    location: "Girona, Spain / Acre, Land of Israel",
    bio: "Leading scholar of medieval Spain. Combined Talmudic mastery with kabbalistic knowledge. Defended Judaism in the Barcelona Disputation (1263). Emigrated to the Land of Israel in his final years.",
    works: ["Ramban on Torah", "Milchamot Hashem", "Torat HaAdam"],
  },
  {
    name_en: "Rabbeinu Tam (Yaakov ben Meir)",
    name_he: "רבינו תם (יעקב בן מאיר)",
    era: "Rishon",
    community: "Ashkenazi",
    birth_year: "1100",
    death_year: "1171",
    location: "Ramerupt, France",
    bio: "Grandson of Rashi and the greatest of the Tosafists. His analytical approach shaped all subsequent Talmud study. His views on tefillin order differ from Rashi's.",
    works: ["Tosafot", "Sefer HaYashar"],
  },
  {
    name_en: "Rif (Yitzchak Alfasi)",
    name_he: "רי\"ף (יצחק אלפסי)",
    era: "Rishon",
    community: "Sephardi",
    birth_year: "1013",
    death_year: "1103",
    location: "Fez, Morocco / Lucena, Spain",
    bio: "Author of the Sefer HaHalachot, a condensed version of the Talmud retaining only practical halachic conclusions. One of the three pillars upon which the Shulchan Arukh was based.",
    works: ["Sefer HaHalachot"],
  },
  {
    name_en: "Rosh (Asher ben Yechiel)",
    name_he: "רא\"ש (אשר בן יחיאל)",
    era: "Rishon",
    community: "Ashkenazi",
    birth_year: "1250",
    death_year: "1327",
    location: "Germany / Toledo, Spain",
    bio: "Leading Ashkenazi authority who moved to Spain. Combined Ashkenazi and Sephardi traditions. One of the three pillars upon which the Shulchan Arukh was based.",
    works: ["Piskei HaRosh", "Tosafot HaRosh"],
  },
  {
    name_en: "Rashba (Shlomo ben Aderet)",
    name_he: "רשב\"א (שלמה בן אדרת)",
    era: "Rishon",
    community: "Sephardi",
    birth_year: "1235",
    death_year: "1310",
    location: "Barcelona, Spain",
    bio: "Student of the Ramban. Leading authority of Spanish Jewry. Authored thousands of responsa. Issued a famous ban on the study of philosophy by those under 25.",
    works: ["Teshuvot HaRashba", "Chiddushei HaRashba"],
  },
  {
    name_en: "Ran (Nissim of Girona)",
    name_he: "ר\"ן (נסים גירונדי)",
    era: "Rishon",
    community: "Sephardi",
    birth_year: "1320",
    death_year: "1376",
    location: "Girona / Barcelona, Spain",
    bio: "One of the last great Rishonim of Spain. His commentary on the Rif is a primary source for understanding the Talmud. Also authored 'Derashot HaRan' on Jewish philosophy.",
    works: ["Chiddushei HaRan", "Derashot HaRan"],
  },
  {
    name_en: "Tur (Yaakov ben Asher)",
    name_he: "טור (יעקב בן אשר)",
    era: "Rishon",
    community: "Ashkenazi",
    birth_year: "1269",
    death_year: "1343",
    location: "Germany / Toledo, Spain",
    bio: "Son of the Rosh. Authored the Arba'ah Turim, which organized all of Jewish law into four sections. This structure was later adopted by the Shulchan Arukh.",
    works: ["Arba'ah Turim"],
  },
  {
    name_en: "Ritva (Yom Tov ben Avraham Asevilli)",
    name_he: "ריטב\"א (יום טוב בן אברהם אשבילי)",
    era: "Rishon",
    community: "Sephardi",
    birth_year: "1250",
    death_year: "1330",
    location: "Seville, Spain",
    bio: "Student of the Rashba and the Ra'ah. His Talmudic novellae are known for their clarity and depth. Important for understanding the Spanish Rishonic tradition.",
    works: ["Chiddushei HaRitva"],
  },
  {
    name_en: "Rabbeinu Yonah of Girona",
    name_he: "רבנו יונה גירונדי",
    era: "Rishon",
    community: "Sephardi",
    birth_year: "1200",
    death_year: "1263",
    location: "Girona, Spain",
    bio: "Cousin of the Ramban. Famous for his work on repentance, Sha'arei Teshuvah. Initially opposed the Rambam's works but later publicly retracted.",
    works: ["Sha'arei Teshuvah"],
  },
  {
    name_en: "Ra'avad (Avraham ben David)",
    name_he: "ראב\"ד (אברהם בן דוד)",
    era: "Rishon",
    community: "Sephardi",
    birth_year: "1125",
    death_year: "1198",
    location: "Posquieres, Provence",
    bio: "Leading scholar of Provence. Famous for his critical glosses (hasagot) on the Rambam's Mishneh Torah. Also a kabbalist and head of a major yeshiva.",
    works: ["Hasagot HaRa'avad"],
  },
  {
    name_en: "Meiri (Menachem ben Shlomo)",
    name_he: "המאירי (מנחם בן שלמה)",
    era: "Rishon",
    community: "Sephardi",
    birth_year: "1249",
    death_year: "1315",
    location: "Perpignan, Provence",
    bio: "Known for his encyclopedic Talmudic commentary 'Beit HaBechirah,' which systematically summarizes all opinions. His works were lost for centuries and rediscovered in modern times.",
    works: ["Beit HaBechirah"],
  },

  // --- Acharonim (early) ---
  {
    name_en: "Yosef Karo",
    name_he: "יוסף קארו",
    era: "Acharon",
    community: "Sephardi",
    birth_year: "1488",
    death_year: "1575",
    location: "Spain / Turkey / Safed, Land of Israel",
    bio: "Author of the Shulchan Arukh, the most authoritative code of Jewish law. Also authored the Beit Yosef, a comprehensive commentary on the Tur. Member of the Safed kabbalistic circle.",
    works: ["Shulchan Arukh", "Beit Yosef", "Kesef Mishneh"],
  },
  {
    name_en: "Moshe Isserles (Rema)",
    name_he: "משה איסרליש (רמ\"א)",
    era: "Acharon",
    community: "Ashkenazi",
    birth_year: "1530",
    death_year: "1572",
    location: "Krakow, Poland",
    bio: "Added Ashkenazi glosses (the Mappah) to the Shulchan Arukh, making it accepted by all Jewish communities. Also authored Darkhei Moshe on the Tur.",
    works: ["Rema on Shulchan Arukh", "Darkhei Moshe"],
  },
  {
    name_en: "Vilna Gaon (Eliyahu of Vilna)",
    name_he: "הגר\"א (אליהו מוילנא)",
    era: "Acharon",
    community: "Lithuanian",
    birth_year: "1720",
    death_year: "1797",
    location: "Vilna, Lithuania",
    bio: "Towering genius of the 18th century. Mastered all areas of Torah by a young age. His commentary on the Shulchan Arukh traces every ruling back to its Talmudic source. Opposed the Chassidic movement.",
    works: ["Bi'ur HaGra"],
  },
  {
    name_en: "Baal Shem Tov (Yisrael ben Eliezer)",
    name_he: "בעל שם טוב (ישראל בן אליעזר)",
    era: "Acharon",
    community: "Chassidic",
    birth_year: "1698",
    death_year: "1760",
    location: "Okopy / Medzhybizh, Ukraine",
    bio: "Founder of the Chassidic movement. Emphasized joy in worship, divine immanence, and the spiritual potential of every Jew regardless of scholarly achievement. His teachings were transmitted by his students.",
    works: [],
  },
  {
    name_en: "Shneur Zalman of Liadi",
    name_he: "שניאור זלמן מלאדי",
    era: "Acharon",
    community: "Chabad",
    birth_year: "1745",
    death_year: "1812",
    location: "Liadi / Liozna, Belarus",
    bio: "Founder of Chabad Chassidism. Authored the Tanya, a foundational work of Chassidic philosophy, and the Shulchan Arukh HaRav, an authoritative halachic code.",
    works: ["Tanya", "Shulchan Arukh HaRav"],
  },
  {
    name_en: "Nachman of Breslov",
    name_he: "נחמן מברסלב",
    era: "Acharon",
    community: "Breslov",
    birth_year: "1772",
    death_year: "1810",
    location: "Medzhybizh / Breslov / Uman, Ukraine",
    bio: "Great-grandson of the Baal Shem Tov. Founded the Breslov Chassidic movement. Known for his mystical tales and emphasis on personal prayer (hitbodedut). Never appointed a successor.",
    works: ["Likutey Moharan"],
  },
  {
    name_en: "Yisrael Meir Kagan (Chofetz Chaim)",
    name_he: "ישראל מאיר הכהן (חפץ חיים)",
    era: "Acharon",
    community: "Lithuanian",
    birth_year: "1838",
    death_year: "1933",
    location: "Radin, Belarus",
    bio: "Authored the Mishnah Berurah, the primary commentary on the Orach Chaim section of the Shulchan Arukh. Also wrote Chofetz Chaim on the laws of speech. Revered for his piety and humility.",
    works: ["Mishnah Berurah", "Chofetz Chaim", "Bi'ur Halacha"],
  },
  {
    name_en: "Yechezkel Landau",
    name_he: "יחזקאל לנדא",
    era: "Acharon",
    community: "Ashkenazi",
    birth_year: "1713",
    death_year: "1793",
    location: "Prague, Bohemia",
    bio: "Chief Rabbi of Prague. Authored the Noda BiYehudah, one of the most important collections of responsa. Known for his balanced approach between stringency and leniency.",
    works: ["Noda BiYehudah"],
  },
  {
    name_en: "Moshe Sofer (Chatam Sofer)",
    name_he: "משה סופר (חתם סופר)",
    era: "Acharon",
    community: "Hungarian",
    birth_year: "1762",
    death_year: "1839",
    location: "Pressburg (Bratislava), Hungary",
    bio: "Leading opponent of the Reform movement. His motto 'Chadash asur min haTorah' (the new is forbidden by the Torah) became a rallying cry for Orthodox resistance to religious reform.",
    works: ["Teshuvot Chatam Sofer", "Chiddushei Chatam Sofer"],
  },
  {
    name_en: "Yonatan Eybeschutz",
    name_he: "יהונתן אייבשיץ",
    era: "Acharon",
    community: "Ashkenazi",
    birth_year: "1690",
    death_year: "1764",
    location: "Krakow / Metz / Altona, Germany",
    bio: "Brilliant scholar and preacher. Authored Ya'arot Devash and other works. Known for the controversy with Rabbi Yaakov Emden over Sabbatean amulets.",
    works: ["Ya'arot Devash", "Urim V'Tumim", "Kreiti U'Pleiti"],
  },
  {
    name_en: "Yaakov Emden",
    name_he: "יעקב עמדין",
    era: "Acharon",
    community: "Ashkenazi",
    birth_year: "1697",
    death_year: "1776",
    location: "Altona, Germany",
    bio: "Son of the Chacham Tzvi. Fierce opponent of Sabbateanism. Known for his encyclopedic knowledge and independent thinking. Authored a famous annotated siddur.",
    works: ["She'elat Ya'avetz", "Siddur Beit Yaakov"],
  },
  {
    name_en: "Chaim Yosef David Azulai (Chida)",
    name_he: "חיד\"א (חיים יוסף דוד אזולאי)",
    era: "Acharon",
    community: "Sephardi",
    birth_year: "1724",
    death_year: "1806",
    location: "Jerusalem / Livorno, Italy",
    bio: "Prolific Sephardi scholar who traveled widely as an emissary. Authored over 70 works on halacha, kabbalah, and bibliography. His Shem HaGedolim is a biographical encyclopedia of rabbinic scholars.",
    works: ["Shem HaGedolim", "Birkei Yosef"],
  },
  {
    name_en: "Yosef Chaim of Baghdad (Ben Ish Chai)",
    name_he: "יוסף חיים מבגדאד (בן איש חי)",
    era: "Acharon",
    community: "Iraqi",
    birth_year: "1835",
    death_year: "1909",
    location: "Baghdad, Iraq",
    bio: "Leading Sephardi-Mizrachi authority. Authored Ben Ish Chai, which combines halacha with kabbalah for each weekly Torah portion. His rulings are followed throughout the Mizrachi world.",
    works: ["Ben Ish Chai", "Rav Pe'alim"],
  },
  {
    name_en: "Avraham Yeshayahu Karelitz (Chazon Ish)",
    name_he: "אברהם ישעיהו קרליץ (חזון איש)",
    era: "Acharon",
    community: "Lithuanian",
    birth_year: "1878",
    death_year: "1953",
    location: "Kosava, Belarus / Bnei Brak, Israel",
    bio: "Leading halachic authority of the early State of Israel period. Lived an ascetic life devoted entirely to Torah study. His rulings on agricultural laws for the Land of Israel are widely followed.",
    works: ["Chazon Ish"],
  },
  {
    name_en: "Yisrael Meir Lau",
    name_he: "ישראל מאיר לאו",
    era: "Modern",
    community: "Ashkenazi",
    birth_year: "1937",
    death_year: "",
    location: "Piotrków / Tel Aviv, Israel",
    bio: "Holocaust survivor, former Ashkenazi Chief Rabbi of Israel (1993-2003). Authored works on practical halacha and Jewish thought.",
    works: [],
  },
  {
    name_en: "Ovadia Yosef",
    name_he: "עובדיה יוסף",
    era: "Modern",
    community: "Sephardi",
    birth_year: "1920",
    death_year: "2013",
    location: "Baghdad / Jerusalem, Israel",
    bio: "Greatest Sephardi posek of the modern era. Sephardi Chief Rabbi of Israel (1973-1983). His Yabia Omer responsa restored Sephardi halachic independence from Ashkenazi influence.",
    works: ["Yabia Omer", "Yechaveh Da'at", "Halichot Olam"],
  },
  {
    name_en: "Moshe Feinstein",
    name_he: "משה פיינשטיין",
    era: "Modern",
    community: "Lithuanian",
    birth_year: "1895",
    death_year: "1986",
    location: "Luban, Belarus / New York, USA",
    bio: "Preeminent halachic authority of American Jewry. His Igrot Moshe responsa address modern questions with remarkable clarity and breadth. Rosh Yeshiva of Mesivtha Tifereth Jerusalem.",
    works: ["Igrot Moshe"],
  },
  {
    name_en: "Yosef Shalom Elyashiv",
    name_he: "יוסף שלום אלישיב",
    era: "Modern",
    community: "Lithuanian",
    birth_year: "1910",
    death_year: "2012",
    location: "Jerusalem, Israel",
    bio: "Leading Lithuanian posek in Israel for decades. Known for his encyclopedic knowledge and extremely precise rulings. Grandson-in-law of the Leshem (Rav Shlomo Elyashiv).",
    works: ["Kovetz Teshuvot"],
  },
  {
    name_en: "Shlomo Zalman Auerbach",
    name_he: "שלמה זלמן אויערבך",
    era: "Modern",
    community: "Jerusalem",
    birth_year: "1910",
    death_year: "1995",
    location: "Jerusalem, Israel",
    bio: "Leading Jerusalem posek renowned for his rulings on electricity, technology, and medicine on Shabbat. Rosh Yeshiva of Kol Torah. Known for his warmth and accessibility.",
    works: ["Minchat Shlomo"],
  },
  {
    name_en: "Eliezer Waldenberg",
    name_he: "אליעזר וולדנברג",
    era: "Modern",
    community: "Jerusalem",
    birth_year: "1915",
    death_year: "2006",
    location: "Jerusalem, Israel",
    bio: "Leading authority on medical halacha. His Tzitz Eliezer responsa are the primary source for medical-halachic questions. Served as dayan on the Jerusalem Beit Din.",
    works: ["Tzitz Eliezer"],
  },
  {
    name_en: "Menachem Mendel Schneerson",
    name_he: "מנחם מנדל שניאורסון",
    era: "Modern",
    community: "Chabad",
    birth_year: "1902",
    death_year: "1994",
    location: "Nikolaev, Ukraine / Berlin / New York, USA",
    bio: "Seventh and last Rebbe of the Chabad-Lubavitch movement. Transformed Chabad into a worldwide movement with emissaries in every major city. His teachings span all areas of Torah.",
    works: ["Likutei Sichot", "Igrot Kodesh"],
  },
  {
    name_en: "Yitzchak Yosef",
    name_he: "יצחק יוסף",
    era: "Modern",
    community: "Sephardi",
    birth_year: "1952",
    death_year: "",
    location: "Jerusalem, Israel",
    bio: "Son of Rav Ovadia Yosef. Current Sephardi Chief Rabbi of Israel. Author of Yalkut Yosef, a comprehensive halachic compendium following his father's rulings.",
    works: ["Yalkut Yosef"],
  },
  {
    name_en: "Avraham Yitzchak Kook",
    name_he: "אברהם יצחק הכהן קוק",
    era: "Modern",
    community: "General",
    birth_year: "1865",
    death_year: "1935",
    location: "Griva, Latvia / Jaffa / Jerusalem",
    bio: "First Ashkenazi Chief Rabbi of British Mandatory Palestine. Visionary thinker who saw the return to Zion as the beginning of divine redemption. Bridged religious and secular communities.",
    works: ["Orot", "Orot HaKodesh"],
  },
  {
    name_en: "Tzvi Yehudah Kook",
    name_he: "צבי יהודה הכהן קוק",
    era: "Modern",
    community: "General",
    birth_year: "1891",
    death_year: "1982",
    location: "Jerusalem, Israel",
    bio: "Son of Rav Kook. Rosh Yeshiva of Mercaz HaRav. His teachings inspired the Religious Zionist settlement movement. Emphasized the holiness of the Land of Israel and the State.",
    works: [],
  },
];

async function main() {
  console.log("=== Populate Rabbis ===\n");

  // Check for existing rabbis
  const existing = await getRabbis();
  if (existing.length > 0) {
    console.log(`Found ${existing.length} existing rabbis in database.`);
    const arg = process.argv[2];
    if (arg !== "--force") {
      console.log("Use --force to re-insert. Skipping.");
      await pool.end();
      return;
    }
    console.log("--force flag detected. Inserting (duplicates may occur).\n");
  }

  let inserted = 0;
  let worksInserted = 0;

  for (const r of RABBIS) {
    try {
      const rabbi = await insertRabbi({
        name_en: r.name_en,
        name_he: r.name_he,
        era: r.era,
        generation: r.generation,
        community: r.community,
        birth_year: r.birth_year,
        death_year: r.death_year,
        location: r.location,
        bio: r.bio,
      });
      inserted++;

      // Insert works
      for (const workName of r.works) {
        await pool.query(
          `INSERT INTO rabbi_works (rabbi_id, work_name) VALUES ($1, $2)
           ON CONFLICT DO NOTHING`,
          [rabbi.id, workName]
        );
        worksInserted++;
      }

      console.log(`  [+] ${r.name_en} (${r.era}) — ${r.works.length} works`);
    } catch (err) {
      console.error(`  [!] Failed to insert ${r.name_en}:`, (err as Error).message);
    }
  }

  console.log(`\nDone. Inserted ${inserted} rabbis, ${worksInserted} works.`);
  await pool.end();
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
